//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/XMLSchema1.xsd", IsNullable=false)]
public partial class CalisanlarSchema {
    
    private CalisanlarSchemaCalisan[] calisanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Calisan")]
    public CalisanlarSchemaCalisan[] Calisan {
        get {
            return this.calisanField;
        }
        set {
            this.calisanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/XMLSchema1.xsd")]
public partial class CalisanlarSchemaCalisan {
    
    private string sicil_NoField;
    
    private string adField;
    
    private string soyadField;
    
    private string gorev_TipiField;
    
    private string sifreField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Sicil_No {
        get {
            return this.sicil_NoField;
        }
        set {
            this.sicil_NoField = value;
        }
    }
    
    /// <remarks/>
    public string ad {
        get {
            return this.adField;
        }
        set {
            this.adField = value;
        }
    }
    
    /// <remarks/>
    public string soyad {
        get {
            return this.soyadField;
        }
        set {
            this.soyadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string gorev_Tipi {
        get {
            return this.gorev_TipiField;
        }
        set {
            this.gorev_TipiField = value;
        }
    }
    
    /// <remarks/>
    public string sifre {
        get {
            return this.sifreField;
        }
        set {
            this.sifreField = value;
        }
    }
}
