//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Hastalar.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/Hastalar.xsd", IsNullable=false)]
public partial class HastalarSchema {
    
    private HastalarSchemaHasta[] hastaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Hasta")]
    public HastalarSchemaHasta[] Hasta {
        get {
            return this.hastaField;
        }
        set {
            this.hastaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/Hastalar.xsd")]
public partial class HastalarSchemaHasta {
    
    private double tcField;
    
    private string adField;
    
    private string soyadField;
    
    private System.DateTime dogum_TarihiField;
    
    private string oldugu_AsilarField;
    
    /// <remarks/>
    public double TC {
        get {
            return this.tcField;
        }
        set {
            this.tcField = value;
        }
    }
    
    /// <remarks/>
    public string ad {
        get {
            return this.adField;
        }
        set {
            this.adField = value;
        }
    }
    
    /// <remarks/>
    public string soyad {
        get {
            return this.soyadField;
        }
        set {
            this.soyadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dogum_Tarihi {
        get {
            return this.dogum_TarihiField;
        }
        set {
            this.dogum_TarihiField = value;
        }
    }
    
    /// <remarks/>
    public string oldugu_Asilar {
        get {
            return this.oldugu_AsilarField;
        }
        set {
            this.oldugu_AsilarField = value;
        }
    }
}
